### ISSUE TITLE
[JS] Sign up for Skygear hosting (2)

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#158]
- add screenshot showing the endpoint and API key
- [Optional] Can add a signup button, example: [Heroku getting started](https://devcenter.heroku.com/articles/getting-started-with-python#introduction)

**Comment by TakLee96** [comment]
I have added an image, but it is too big to be displayed. Shall we add CSS to make sure the image is displayed correctly? ![demo](https://s31.postimg.org/6y07s32zd/2016_07_19_10_53_26.png)
