### ISSUE TITLE
[JS] edit section: Start a new JS project (4)

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#159]
- Add intro: you need to install and import the js sdk to start writing a skygear JS app.
- Make it look like a step-wise guide
- Tell user to install the stable release on npm. Collapse dev version section (if possible)
- to include a link for the scaffolding project for JS SDK

**Comment by TakLee96** [comment]
It seems that currently there doesn't exist a scaffolding project for JS SDK. Shall I create one?

**Comment by TakLee96** [comment]
I'm also confused that where is this `Start a new JS project` section? It's not in the quip menu page, right?

**Comment by bensonby** [comment]
please refer to #161
