### ISSUE TITLE
[JS] edit section: Queries: Basic Queries (2)

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#168]
- Good if have an overview [Firebase save data](https://firebase.google.com/docs/database/web/save-data)
- typo: inside the `private database ` -> `public database `
- Query examples should be shorter
- No need to have the example for reserved columns

**Comment by TakLee96** [comment]
I think it would be nice to notify the users that there are reserved columns and show them the link to read more. This would also put emphasis on the fact that they should query by column name but not JavaScript key/attribute.
