### ISSUE TITLE
[JS] edit section: Queries: Conditions (1)

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#169]
- What are "conditions"?
	- Need to mention "You can specify conditions when making query to the records. It is like the WHERE clause in SQL or filter in NOSQL."
- "Having relation" is unclear
- First example needs to have `let Note = Record.extend("Note")`
- [x] no example for using `LIKE` with `_` wildcard character

**Comment by TakLee96** [comment]
I've put "If you don't know what `Note` is or the difference between
privateDB and publicDB, please read [Records](/js/guide/record) section first." in the first paragraph, so maybe I don't need to declare `Note` again?
