### ISSUE TITLE
[JS] edit section: Users: Under User profile (1)

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#177]
- need to mentionthat the reserved table should not be manipulated; it is for Skygear internal use
- need to state what the `_id` is (user id)
- need to give hint for using privateDB for sensitive user info. and link to the server guide on database which describes more about publicDB and privateDB (from #51)

**Comment by HenryHins** [comment]
Issue #51 is still open and I can't seem the find the publicDB and privteDB guide in the server doc :/
