### ISSUE TITLE
[JS] edit section: Access Control (2)

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#178]
- Restructure the subsections:
	- Overview / Access Type?
   		- Say that there is read/write access for each record
	- Default ACL Settings
	- ACL by User
	- ACL by User Role

**Comment by bensonby** [comment]
to double check if this has been completed

**Comment by TakLee96** [comment]
There is additionally a section on **ACL by Record Type** which current contains information about **Record creation access control**. I have removed the part about `Record.beforeSave(...)`.
