### ISSUE TITLE
[JS] revamp: Use Skygear with ReactJS/AngularJS with Webpack (8)

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#182]
- Aim: When developer uses webpack to bundle their apps (Angular / ReactJS / Electron), they need to follow this set up
- refactor this page
  - not to assume yeoman
- put this inside the getting started page, if it is short enough
- Sections:
  - integrate Skygear with webpack (only essential lines of config, in `external`)
  - a full example webpack config with skygear, react, ES6

**Comment by rickmak** [comment]
Please note that we will have yeoman generator very soon, probably in next release (0.14.0). You may checkout this: https://www.npmjs.com/package/generator-skygear which is working against current master of skygear-SDK-JS.

**Comment by TakLee96** [comment]
@rickmak my current documentation on webpack config is based on your latest PR (I think by now it's been merged) assuming that v0.14.0 will soon be released to npm. Whenever the yeoman generator is ready, let me know and I will definitely include it in the documentation.
