### ISSUE TITLE
content and menu overlapped when clicking in submenu

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#187]
Steps to reproduce:

1. Enter either JS SDK guide / iOS SDK guide / Server guide
2. click on one of the submenu item

<img width="708" alt="screen shot 2016-07-15 at 15 49 33" src="https://cloud.githubusercontent.com/assets/246195/16867323/c8d5084c-4aa3-11e6-9e9a-6a90c3d587ec.png">

**Comment by ben181231** [comment]
Should be fixed on after introducing hamburger menu (on Commit 4605034).
