### ISSUE TITLE
Scrolling through body should trigger submenu item to be highlighted

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#188]
When scrolling in the main body to another section corresponding to the next submenu, the next submenu should be highlighted.

E.g. in the screenshot, the menu should highlight "Basics of Skygear JS SDK", not "Install Skygear JS SDK"

<img width="851" alt="screen shot 2016-07-15 at 15 54 50" src="https://cloud.githubusercontent.com/assets/246195/16867452/86f61c44-4aa4-11e6-9b09-7ec7f02aa8d3.png">

**Comment by TakLee96** [comment]
I know that Bootstrap scrollspy works for this purpose. Not quite sure if we can achieve this with purely CSS. Writing it manually in JS would be hard, right?

**Comment by royuen** [comment]
@TakLee96 are you working on this? Or we could help too

**Comment by TakLee96** [comment]
@royuen haha, got it XD, thanks
