### ISSUE TITLE
Coming soon page should still have the side menu

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#189]

**Comment by TakLee96** [comment]
I think either we have to create a coming-soon page for each doc, or we add a `Go Back` button in the generic coming-soon page.

**Comment by bensonby** [comment]
We will create the corresponding routes in each of the SDK; all of them uses the same coming-soon.md as content

**Comment by bensonby** [comment]
Fixed in 9eabbf5.
