### ISSUE TITLE
Scrolling to bottom of page causes the footer to cover the menu

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#190]
<img width="796" alt="screen shot 2016-07-15 at 16 15 59" src="https://cloud.githubusercontent.com/assets/246195/16867965/7e078bc4-4aa7-11e6-9c39-94b4df435b5a.png">

**Comment by ben181231** [comment]
Fix the overlapping (z-index) issue on Commit e068894.

But, is the footer overlapping the content / menu an expected behavior?

@bensonby

**Comment by bensonby** [comment]
they shouldn't overlap

**Comment by bensonby** [comment]
When the menu on the left is sticky, how should the footer/menu behave when a user scrolls to the bottom?

**Comment by bensonby** [comment]
using this way? https://firebase.google.com/docs/web/setup

**Comment by bensonby** [comment]
Obsolete after new doc site deployed
