### ISSUE TITLE
write doc for JS guide atomic batch save option

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#198]
- should we note the version from which it is supported?

https://github.com/SkygearIO/skygear-SDK-JS/commit/8bd8a7c191e7f96c5d95444a6a4caf56294ac259

**Comment by TakLee96** [comment]
@rickmak what's the different between setting atomic to be true and not?

**Comment by bensonby** [comment]
@TakLee96 atomic will mean that either all the records save succesfully or none of them can be saved, i.e. no partial success.

http://stackoverflow.com/questions/15054086/what-does-atomic-mean-in-programming
