### ISSUE TITLE
Advance logging configuration for skygear-server

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-doc#222]
Describe how to config the logger with different level according to https://github.com/SkygearIO/skygear-server/pull/87

Expect for advance user, so it will not in the same page with current config. Which may confuse normal user.

For my personal experience, this two config is most wanted.

LOG_LEVEL_PLUGIN=
LOG_LEVEL_PUBSUB=

**Comment by chpapa** [comment]
This issue was moved to SkygearIO/guides#25
