### ISSUE TITLE
anchor name vs id

### ISSUE THREAD

**Issue by TakLee96** [SkygearIO/skygear-doc#228]
It seems that all the headers in markdown file will be compiled into html with an id, so to make the menu links work (e.g. `/js/guide/record#basic-crud`) there are three ways to do it:
- Add `<a name='basic-crud'></a>` above the header
- Add `<a id='basic-crud'></a>` above the header
- Do nothing and use the auto-compiled id (if we do it this way, then the doc page header would "eat" the header)

Which one should we use?

**Comment by bensonby** [comment]
The new markdown renderer markdown-it will not automatically assign an id to the html header tag. We should use `id` for all these anchors.
