### ISSUE TITLE
Add indicator icon for external sites

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#243]
Example:

<img width="632" alt="screen shot 2016-07-28 at 16 10 48" src="https://cloud.githubusercontent.com/assets/246195/17205481/e2fc4aa2-54dd-11e6-8f5a-b1281f3df6db.png">

**Comment by TakLee96** [comment]
Also, clicking on the links do not open up a new tab but just redirect the current tab to the linked address. I think for certain links, such as Sign Up at Portal or Babel, it's better to simply open up a new tab.

**Comment by chpapa** [comment]
It will be addressed by #425
