### ISSUE TITLE
[JS] write doc for `getRecordByID`

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#247]

**Comment by tensiuyan** [comment]
@chpapa can you help to identify which guide should this issue be related to?

**Comment by chpapa** [comment]
I think it should be:
https://docs.skygear.io/guides/cloud-db/basics/js/
https://docs.skygear.io/guides/cloud-db/queries/js/

**Comment by chpapa** [comment]
This issue was moved to SkygearIO/guides#24
