### ISSUE TITLE
[Server] Describe necessary AWS S3 settings for asset upload

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#287]
https://github.com/SkygearIO/skygear-SDK-JS/issues/48#issuecomment-238773868

**Comment by tensiuyan** [comment]
@chpapa can you help me to identify which guide should this issue be going? thanks

**Comment by chpapa** [comment]
Should be there: https://docs.skygear.io/guides/advanced/server/

**Comment by chpapa** [comment]
This issue was moved to SkygearIO/guides#23
