### ISSUE TITLE
Improve JS kickstart guide to mention node & npm versions, and what next

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-doc#303]
- Need to state required node & npm version in the docs
- Need to add what to do next steps in the docs

**Comment by rickmak** [comment]
See https://github.com/SkygearIO/generator-skygear/commit/8c573145fb11a646ebbc7c92b662b75dbfe1f011 and https://github.com/SkygearIO/generator-skygear/commit/b095469760e5cd08e78765c332c7c2e6041655f8
