### ISSUE TITLE
How to duplicate a record

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-doc#314]
In Skygear, the record behave as follow:
1. `_id` is the only identifier for record. So different ID will be different record.
2. That is, if you do following, there will be two note with same content created

```
const note = new skygear.Record.extend('note');
note.content = 'Some duplicated content';
skygear.publicDB.save(note);
note._id = 'newidnotrequiredtobeuuid';
skygear.publicDB.save(note);
```

So duplicate record in skygear just need to assign a new `_id` as you suggest.
Therefor we can do this:

```
note // query from skygear.publicDB.query
const noteJSON = note.toJSON();
delete noteJSON['_id'];
const duplicatedNote = new Note(noteJSON);
```

**Comment by rickmak** [comment]
@bensonby do we have similar section? or we need to add it to doc.

**Comment by bensonby** [comment]
@rickmak we don't, will need to add to doc.

**Comment by rickmak** [comment]
Which section should I add to? Or FAQ?

**Comment by bensonby** [comment]
I think it can be in the Records page, perhaps we need a section just to talk about the `id`?

**Comment by chpapa** [comment]
Need it for all client SDK doc, add a checklist on description?

**Comment by chpapa** [comment]
This issue was moved to SkygearIO/guides#22
