### ISSUE TITLE
Atomic save deserve it own's sub header

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-doc#315]
https://docs.skygear.io/js/guide/record/

Now it is under "CRUD" > Batch Save, so it is sub-sub header. Since it is important I think it is fair to say it should be on TOC?

Same goes to Andorid and iOS guide

**Comment by chpapa** [comment]
Maybe we should also give better explanation:

1. Now it said "good" and "bad" save, I think it meant saved successfully or an error.

2. I think it would be good to give some example of how to solve common racing condition with atomic increment counter.

Not sure how to structure all these paragraphs would be better actually, so this issue is more like an question.

**Comment by bensonby** [comment]
Included in #304
