### ISSUE TITLE
Assets access control not being cleared enough (skygear server)

### ISSUE THREAD

**Issue by klam00** [SkygearIO/skygear-doc#328]
Whilst trying to find a way to set my assets to public, js sdk doc had no mentions of how the permissions work for assets. It would be helpful if there is some text, link or reference to the existing server doc how-to.

**Comment by tensiuyan** [comment]
@klam00 you can make direct edits here: https://github.com/SkygearIO/skygear-doc/blob/master/content/cloud-function/static-assets/python.md
