### ISSUE TITLE
[JS] Cloud functions page.

### ISSUE THREAD

**Issue by klam00** [SkygearIO/skygear-doc#332]
https://docs.skygear.io/js/guide/cloud-functions

**Comment by tensiuyan** [comment]
Should this be empty or are we planning to have a cloud functions guide for JS in the near future? @chpapa

**Comment by chpapa** [comment]
@tensiuyan I think we shall expect to have cloud function JS guide in near future, once we move away from focusing on Chat...

**Comment by chpapa** [comment]
This issue was moved to SkygearIO/guides#21
