### ISSUE TITLE
Broken link on Command Line Tools - Usage

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-doc#35]
To reproduce,

1. Go to http://docs-staging.skygear.io/cli/guide#
2. Click Usage on the left.
3. Browser not redirected to the new page (unexpected)
4. Click the Usage link at the bottom on the screen
5. Browser navigated to `http://docs-staging.skygear.io/cli/{{%3C%20relref%20%22usage.md%22%3E}}` (unexpected)

(3) and (5) should point the browser to the usage page?

**Comment by rickmak** [comment]
Close via 164a6b1
