### ISSUE TITLE
[JS] query page improvement

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#350]
(from quip)
- Info on Record objects:
  - Explain that Records aren't plain JS objects
  - Fields are accessible via JS getters, printing the object will not show user data.
  - The toJSON method is implemented, JSON fields can't be used in JS.
- Give example on how to break promise chain on multi-query operations
- add doc for `getRecordByID` #247

**Comment by chpapa** [comment]
This issue was moved to SkygearIO/guides#19
