### ISSUE TITLE
Restructure docs.skygear.io

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-doc#369]
The current structure of docs.skygear.io is kind of out-dated and internally we keep complain the styling make it very difficult to read. So a restructure of the docs and style is needed.

Here are my proposal for the re-structuring.

## docs.skygear.io
We should have a few types of docs, each with links from the main page:
* Guides - it should be the major way new comers learn about Skygear
* References - Technical API references
* How to - Step by step walk throughs to learn something

## Guides
Guides should be grouped as following:
1. Skygear Auth
1. Skygear Cloud DB
1. Skygear Pubsub
1. Skygear CMS
1. Skygear Chat
1. Skygear Push
1. Skygear Cloud Functions
1. FAQ

For 1 - 6, each guides should have 3 version: iOS, Android, Web;
For 7, each guides should have 2 version: Python and Javascript.

Number of Guides under each features can be various and unlimited, the design should cater for it.

Under each guides there could be 3 level of headers. The length of each guides could be various too.

For iOS, there are Objective-C and Swift sample code on the same guide.

### Open Questions on Guides
* Shall we include portal.skygear.io usage in each languages of guides? Or should guides have 3 platform + a general one for portal.skygear.io explanation? 

## References
References are assume to be generated docs from different programming languages. 

## How to
How to are step by step walk throughs; Sample projects should be here.

## Design styling
* Should have proper styling for Tips / Advanced / Warning box #364

**Comment by bensonby** [comment]
@chpapa What are some examples of step-by-step walkthroughs? Do we have any of them now?

**Comment by chpapa** [comment]
@bensonby Hmmm, I think May was trying to make some, but not finalized yet.

I guess we don't have to consider them too much on the new doc site yet, maybe just leave it as one of the tab, and link it to a wordpress blog or quip docs.

**Comment by bensonby** [comment]
Closing this after the deployment to production site. Will create separate issues for any outstanding tasks
