### ISSUE TITLE
Change the pem generate guide to generate pem without password

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-doc#371]
Current link to pem generate guide don't teach how to generate a .pem without password. And skygear-server don't accept pem with password.

The tutorial link appear at following location.
https://docs.skygear.io/server/guide
http://portal.skygear.io/app/{appName}/settings

**Comment by tensiuyan** [comment]
@rickmak May I know which guide is this issue related to? The link in this issue no longer exists. Thanks. (Just trying to label the issues and arrange the task. Many many thanks)

**Comment by mayyuen318** [comment]
Kindly remove/update the link (https://docs.skygear.io/server/guide) .... see 404 report again  @rickmak

**Comment by rickmak** [comment]
@tensiuyan I can no longer find any pem related text in current doc. Probably got removed.....

All push notification related guide are client side. Server side guide disappeared.

**Comment by chpapa** [comment]
@rickmak feel free to propose if we need to put server guide up again. When Benson revamp the doc site some got ignored...

**Comment by chpapa** [comment]
This issue was moved to SkygearIO/guides#18
