### ISSUE TITLE
`from skygear.pubsub import publish` does not work without api_key in PUBSUB_URL

### ISSUE THREAD

**Issue by lampercy** [SkygearIO/skygear-doc#411]
In https://docs.skygear.io/plugin/guide/pubsub, 
it suggests using 
```from skygear.pubsub import publish ``` 
to do pubsub

but it works only when I add the api_key to PUBSUB_URL
So is it better to use 
```
from skygear.pubsub import Hub
Hub(api_key=skyoptions.apikey)
``` 
instead?

**Comment by rickmak** [comment]
In cloud deployment, the apikey should properly set. If you are using local deployment, just set the `API_KEY` in your docker-compose will works. No need to create your own `Hub` instance.
