### ISSUE TITLE
Hamburger menu should close itself upon clicking on guide titles or empty space

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#418]

**Comment by david90** [comment]
Or have a close button?

**Comment by rickmak** [comment]
Clicking the link at Hamburger menu will close itself with animation. It is good to have too?

**Comment by chpapa** [comment]
This issue will be outdated with new design

**Comment by rickmak** [comment]
Current deployment still have this problem.

**Comment by chpapa** [comment]
Yes, but Ten is working on an updated design which will need Skygear Dev team help implement it in next iteration #462 . So I'm closing this issue as the updated design will obviously obsoleted this.
