### ISSUE TITLE
Write an guide on how to set up Skygear and Skygear cloud

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-doc#421]
Moved from skygeario/skygear-server#260

Now there is no explicit guide on how to set up Skygear Server and cloud dev

**Comment by royuen** [comment]
Mac / Unix for local development

- [ ] Teach how to run skygear-server binary
- [ ] Teach how to install psql (may be a link)
- [ ] Teach how to run cloud code

**Comment by david90** [comment]
## Get Skygear

### Set up PostgresSQL database in your local machine
* Mac version(easiest way): Install postgresSQL with postgresapp.com

### Download Skygear Binary from GitHub
* https://github.com/SkygearIO/skygear-server/releases
* Mac: Download skygear-server-darwin-amd64 version
* Unix: Download the binary accord to your architecture

### Set up these env variables
```
export DATABASE_URL="postgresql://postgres:@localhost/postgres?sslmode=disable"
export API_KEY="changeme"
export MASTER_KEY="secret"
export APP_NAME="_"
export PLUGINS="JS"
export JS_TRANSPORT="http"
export JS_PATH="http://localhost:9000"
export TOKEN_STORE="jwt"
export TOKEN_STORE_SECRET="jwt_secret"
```


### Run skygear with command line tool


## Install Skygear Cloud Code (JS)

### Install Skygear SDK with NPM:
* Run `npm install skygear`

### Set up these env variables
```
export PUBSUB_URL="ws://localhost:3000/pubsub"
export SKYGEAR_ENDPOINT="http://localhost:3000"
export HTTP="true"
```

### Run `skygear-node` in your project folder
* Skygear will look for index.js and run your code

## Deploy your cloud code
* Push your code to master branch of your Skygear.io git endpoint

**Comment by chpapa** [comment]
@david90 Is it heavily overlap with this old guide? https://github.com/SkygearIO/skygear-doc/blob/before-restructure/content/server/configuring.md

if yes please reference and update #420 too

**Comment by chpapa** [comment]
Please also look at #38 and see if that part should be revised together.

**Comment by seventhmoon** [comment]
Please also add information about database connection config / db user requirement (require superuser?)

**Comment by david90** [comment]
I have put up an updated draft on [quip](https://oursky.quip.com/WoykABqUWhHH), @rickmak @chpapa please take a look (and add/change anything) 

If it's alright we may put up a draft asap.

**Comment by chpapa** [comment]
@david90 I think it's better to collaborate on github instead of Quip? I have created PR #451 for that purpose.

**Comment by chpapa** [comment]
FYI: Old guide https://github.com/SkygearIO/skygear-doc/blob/before-restructure/content/server/configuring.md
