### ISSUE TITLE
Chat Introduction Guide

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-doc#422]
maybe links to relevant section of API ref?

**Comment by chpapa** [comment]
* Enabling on Chat Plugin on Skygear Portal (Enabling Chat plugin on Skygear Chat and installing the corresponding SDK will get you started with Skygear Chat. )
* Creating Conversations
  * Creating Direct Conversations 
  * Creating Group Conversations
  * Creating Group Chat by DistinctParticipants (distinctByParticipants)
  * Leaving Conversaions 
* Managing Chat Participlants
  * Adding users to conversation 
  * Removing users from conversation 
  * Admin 
* Sending Messages
  * Plain Text 
  * Metadata 
  * Files 
* Subcribing to new messages
  * Subscribing to messages in a conversation 
  * Subscribing to messages in all conversations 
* Displaying Unread Count
  * Conversation unread count 
  * Overall Unread count 
* Typing Indicator
  * Subscribing to typing indicator 
  * Sending my typing status 
* Chat History
  * Loading all messages from a conversation 
* Recipient Status
  * Message status 
  * Subscribing to message status change 
  * Marking messages as read
* Push Notification
  * Sending push notifications to conversation participants 
  * Receiving push notifications 
* User Online Indicator
  * User online indicator status 
  * Subscribing to user online indicator
* Best Practices
  * Displaying last messages in a conversation list 
  * Caching message history locally 
  * Handling edit and delete messages

**Comment by rickmak** [comment]
After issue https://github.com/SkygearIO/chat/issues/76, `Displaying last messages in a conversation list ` will be a feature, not best practices.

**Comment by chpapa** [comment]
Thanks! @david90 please be noted.

**Comment by david90** [comment]
Updated Version
* Enabling on Chat Plugin on Skygear Portal (Enabling Chat plugin on Skygear Chat and installing the corresponding SDK will get you started with Skygear Chat. )
* Creating Conversations
  * Creating Direct Conversations 
  * Creating Group Conversations
  * Creating Group Chat by DistinctParticipants (distinctByParticipants)
  * Leaving Conversaions 
* Managing Chat Participlants
  * Adding users to conversation 
  * Removing users from conversation 
  * Admin 
* Sending Messages
  * Plain Text 
  * Metadata 
  * Files 
* Subcribing to new messages
  * Subscribing to messages in a conversation 
  * Subscribing to messages in all conversations 
* Displaying Unread Count
  * Conversation unread count 
  * Overall Unread count 
* Typing Indicator
  * Subscribing to typing indicator 
  * Sending my typing status 
* Chat History
  * Loading all messages from a conversation 
* Recipient Status
  * Message status 
  * Subscribing to message status change 
  * Marking messages as read
* Displaying last messages in a conversation list 
* Push Notification
  * Sending push notifications to conversation participants 
  * Receiving push notifications 
* User Online Indicator
  * User online indicator status 
  * Subscribing to user online indicator
* Best Practices
  * Caching message history locally 
  * Handling edit and delete messages

**Comment by david90** [comment]
@rickmak will need your advice on 
* Best Practices
 * Caching message history locally
 * Handling edit and delete messages

**Comment by chpapa** [comment]
Should also mention the Chat SDK CDN: http://code.skygear.io/js/chat/latest/skygear-chat.min.js

**Comment by tensiuyan** [comment]
May I know what are the following up items of this issue? If not shall we close it? Or create new issues? So far as I know the chat guide has already been published.

**Comment by david90** [comment]
@tensiuyan I think this has been completed with the Chat Guide published.

**Comment by chpapa** [comment]
Closing this :)

**Comment by KhaledAld** [comment]
hey 
Push Notification is not working on chat (send message from Device A to Device B , Device B don't receive any notification ) 
Sending push notifications to conversation participants
Receiving push notifications

and it's working when i send push manually (SKYAPSNotificationInfo)
???

**Comment by tensiuyan** [comment]
@KhaledAld to send a push notification to the devices when there are new messages you need to register an afterMessageSentHook. Here's the doc: https://docs.skygear.io/guides/chat/cloud-event-hook/js/. Scroll to the bottom and you will find an example.

You can either write this cloud functions in Python or JavaScript. Here's how you can push the code to your app on the Portal: https://docs.skygear.io/guides/cloud-function/intro-and-deployment/.

Closing this issue since it is not a bug. Please reach us on https://discuss.skygear.io/ for support. Thanks!

**Comment by KhaledAld** [comment]
@tensiuyan  
Thanks for ur replay 
this is work for local ? or just on portal ??
