### ISSUE TITLE
[Design Update] Style links in documents

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-doc#425]
It would be really helpful if whenever we link to another guide, there will be a special consistent style, so people can notice it is a link to another guide clearly.

**Comment by chpapa** [comment]
https://www.dropbox.com/s/zxbebfux6tyl1lx/link-style.pdf?dl=0

**Comment by royuen** [comment]
- [ ] Only work on External and Github link, automatically detect and add icon to the link
- [ ] For both external and github link, open a new window
