### ISSUE TITLE
[Quick start] the name "new app" and "existing app" is confusing

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/skygear-doc#429]
Page: 
https://docs.skygear.io/guide/get-started/ios/
https://docs.skygear.io/guide/get-started/android/
https://docs.skygear.io/guide/get-started/js/

Problem: 
The name "new app" and "existing app" is confusing. I actually followed the steps on the "existing app" page to start a new project instead of the "new app" page. After studying the nature of the guide, I suggest we can use the following names:

"new app" - Start with a scaffolding project
"existing app" - Start from scratch

Welcome thoughts. Not very good at naming.

**Comment by chpapa** [comment]
@tensiuyan What about...

"New app from template", and
"Integrate with existing app"?

**Comment by chpapa** [comment]
Closed and move to skygeario/skygear-getstarted#34
