### ISSUE TITLE
Add 404 page not found page

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-doc#441]

**Comment by tensiuyan** [comment]
@chpapa anyone working on this? If not I can talk to SiuTao.

**Comment by chpapa** [comment]
Sure

**Comment by tensiuyan** [comment]
@chpapa 

The design of the 404 page is ready. I hope to have it in the next iteration as we have quite a lot of invalid links out there. 
https://www.dropbox.com/s/kq0bc5fvpyxti4w/skygearDoc-404page-080317.pdf?dl=0

**Comment by chpapa** [comment]
@tensiuyan it's okay ah. But I expect something more funny law! XD

I have also created #500 will wait for 2 weeks, and collect a list of 404 error URLs, so we can set up redirection to the correct URL, and maybe try to find where the old URLs came from.

**Comment by tensiuyan** [comment]
okay it will be funnier in the next iteration lol

**Comment by ben181231** [comment]
Just discussed with @tensiuyan. Remove the links in the middle and change to "Take me home".
