### ISSUE TITLE
Chat related Skygear Features Guide

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-doc#445]
Ten suggested us to add a guide about what Skygear features would be used with Skygear Chat.

This is a tracking issue and commits. The basecamp todo list is at https://public.3.basecamp.com/p/pFjAMu7mdauhXL8AYFAJo4Zr

**Comment by chpapa** [comment]
@tensiuyan May I know why you've decided to close this issue? (Although I believe it is better to include those "frequently used features of chat" in chat guide / chat introduction too.

**Comment by tensiuyan** [comment]
@chpapa ya that's the reason. Should have created issue for the introduction page tho. Let me do it now.
