### ISSUE TITLE
User Profile Doc - add user discoverability and access control

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/skygear-doc#456]
We should add the following items in the user profile guides 
- discoverability of a user
- access control

**Comment by chpapa** [comment]
Consider implement SkygearIO/skygear-server#54 when writing this guide? Many fellows want #54 and have to implement themselves, while this guide are supposed to explain common situations

**Comment by chpapa** [comment]
@rickmak @ben181231 @b123400 who would be assigned for this?

**Comment by chpapa** [comment]
This issue was moved to SkygearIO/guides#9
