### ISSUE TITLE
Doc Site Design Update

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-doc#462]
Here are a list of agreed update items:

- Add a top menu bar for *Support* *API Reference*
- Change the guide list panel to always show on the left, and not overlay
- Add Search Bar on top right
- On the right, add a TOC (like Quip's Outline), the TOC list should float and follow the scroll.
- Guides name will be shorten
- When switch between guides, we should keep staying on the same platform (so clicking User Auth Guide from DB JS Guide should goes to JS User Auth Guide instead of iOS User Auth guide)

Since it will be a 3 column design, here are the expected behavior on responsiveness:

1. Full screen - 3 columns
2. Smaller screen - 2 columns, the right column (TOC) move to top of the main content and not scroll.
3. Mobile screen - 1 column, with the left column (Guide List) become a hamburger menu.

**Comment by chpapa** [comment]
For TOC, I think we can simply use this plugins: 
- https://www.npmjs.com/package/markdown-it-table-of-contents

**Comment by tensiuyan** [comment]
This is the latest design of the doc site.
[SkygearDoc Guides Design (Mobile)-20170223.pdf](https://github.com/SkygearIO/skygear-doc/files/796141/SkygearDoc.Guides.Design.Mobile.-20170223.pdf)
[SkygearDoc Guides Design -20170223.pdf](https://github.com/SkygearIO/skygear-doc/files/796142/SkygearDoc.Guides.Design.-20170223.pdf)

**Comment by ben181231** [comment]
This task is spilt into #492, #493, #494, #495 and #496.
