### ISSUE TITLE
Inline API reference links to all JS guides

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-doc#463]
- [x] #464 Update Skygear Chat JS Guide API ref link as standard. Each update should apply to all platforms guide.
- [x] Chat
- [x] User authentication basics 
- [ ] Social login
- [ ] User profile
- [ ] Cloud database basics
- [ ] Data queries
- [ ] Data type
- [ ] Access control basics
- [ ] Offline storage
- [ ] Query subscription
- [ ] PubSub
- [ ] intro & deployment of CF
- [ ] CF for Database event hooks
- [ ] CF for schedule taks
- [ ] CF for Skygear SDK call
- [ ] CF as HTTP endpoint
- [ ] CF as restful HTTP endpoint
- [ ] Serving static assets
- [ ] Calling Skygear API
- [ ] Authenticating users
- [ ] Error handling
- [ ] User relations basics
- [ ] Skygear CLT
- [ ] Skygear database schema
- [ ] Writing your own auth provider

**Comment by tensiuyan** [comment]
The list is pretty long. Guess it will be good enough to make a list here instead of opening an issue for every doc?

**Comment by chpapa** [comment]
Fine :)

**Comment by chpapa** [comment]
Moved to skygeario/guides#32
