### ISSUE TITLE
What does "currentUser object is only retrieved when user login / signup Skygear." meant?

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-doc#469]
On Skygear doc:

docs.skygear.io/guides/auth/basics/js/

There is a line:

"Please be reminded that the currentUser object is only retrieved when user login / signup Skygear."

What does that meant?

**Comment by rickmak** [comment]
I guess => `Please be reminded that the currentUser object only exist after user login / signup Skygear.`

**Comment by bensonby** [comment]
"Please be reminded that the currentUser object only retrieved when user login / signup Skygear.

To get the latest information (e.g. roles, emails, etc.) of the current user, you can ask "Who am I" to Skygear:"

My meaning is that if the user changes its email or role after logging in, this `currentUser` will not update automatically, perhaps need to be more explicit in this

**Comment by chpapa** [comment]
@rickmak @bensonby Thanks for clarification. Is it really a doc problem, or should the SDK just update it? It seems very very tricky?

**Comment by chpapa** [comment]
May I clarify that:

1) On the same session, currentUser always exists, no matter login was called or not (for example, a saved session)

2) On the same session, if roles / emails was updated, currentUser will update

3) If roles / emails was updated by another session, the current session's currentUser will NOT update

Are all of the above true? @rickmak

**Comment by rickmak** [comment]
Yes, all 3 are true with following details.

1. currentUser will exist. It is persist to to localStorage. Until developer call logout at the session. Notes: `currentUser` will still exist even the session become invalid remotely.
2. If the developer update the user via SDK `container.saveUser` method, current User will update. If he go to just save the `User` Record using `database.save`, currentUser will not update.
3. All remote update will not update the currentUser data. It includes roles, emails, username and last_login time.

**Comment by chpapa** [comment]
@rickmak @bensonby Understood. I will send a Pull Request regarding this edits in minutes.

Besides currentUser of JS, is there a counterpart in iOS / Android?

**Comment by rickmak** [comment]
All SDK will not do remote update. But I am not sure does Android or iOS have a `saveUser` method.

**Comment by chpapa** [comment]
@rickmak @ben181231 can you / point to someone else to help on what's the equivalent of currentUser and whoami() in iOS / Android? Let me update the docs all at once.

**Comment by rickmak** [comment]
Android: https://docs.skygear.io/android/reference/io/skygear/skygear/Container.html#whoami(io.skygear.skygear.AuthResponseHandler)
iOS: http://cocoadocs.org/docsets/SKYKit/0.22.1/Classes/SKYContainer.html#//api/name/getWhoAmIWithCompletionHandler:

**Comment by chpapa** [comment]
This issue was moved to SkygearIO/guides#7
