### ISSUE TITLE
Inline API reference links to all Android guides 

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/skygear-doc#471]
- [ ] Chat
- [ ] User authentication basics 
- [ ] Social login
- [ ] User profile
- [ ] Cloud database basics
- [ ] Data queries
- [ ] Data type
- [ ] Access control basics
- [ ] Offline storage
- [ ] Query subscription
- [ ] PubSub
- [ ] intro & deployment of CF
- [ ] CF for Database event hooks
- [ ] CF for schedule taks
- [ ] CF for Skygear SDK call
- [ ] CF as HTTP endpoint
- [ ] CF as restful HTTP endpoint
- [ ] Serving static assets
- [ ] Calling Skygear API
- [ ] Authenticating users
- [ ] Error handling
- [ ] User relations basics
- [ ] Skygear CLT
- [ ] Skygear database schema
- [ ] Writing your own auth provider

**Comment by chpapa** [comment]
Moved to skygeario/guides#33
