### ISSUE TITLE
Skygear Chat guide for Android

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/skygear-doc#485]
We need 
- [ ] installation guide
- [ ] Skygear chat basics (please refer to the current iOS guide https://docs.skygear.io/guides/chat/basics/ios/)

**Comment by tensiuyan** [comment]
@david90 how's your schedule next week? Do you think you have time to work on the Android guide for Skygear chat?

**Comment by david90** [comment]
@tensiuyan sure, let's schedule in next week (6Mar).

**Comment by chpapa** [comment]
This issue was moved to SkygearIO/guides#3
