### ISSUE TITLE
Add other JS projects set up to the JS quick start

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/skygear-doc#487]
Add back the installation guide for webpack and react native project to the current JS quick start.

**Comment by chpapa** [comment]
It sounds like something we have discussed before -- we need another list of guides / boilerplates for each common JS framework integration...

think we may have a seperate page for all integration guides? And we can have a link to that integration guide from Quickstart's what is next...

I have the list as follows....

- HTML (cdn) + JQuery
- HTML (cdn) + vue.js
- Ionic 2
- Ionic 2 x Webpack
- React Native
- React.js x Webpack
- Angular 2
- Electron
- RPi nodeJS - @akiroz can it be a scaffolding, or more like a tutorial?

**Comment by akiroz** [comment]
A RPi image would probably be the closest thing to a scaffolding, but we probably also need a tutorial to teach the user how to load the image into an SD card on different OS'

**Comment by chpapa** [comment]
@akiroz Sorry I still haven't got time to sit down and read your JS Utility function doc... Will do it this weekend. Meanwhile if you have nothing else better to do, start working on loading Skygear-JS on RPi image and related tutorial is great XD

**Comment by chpapa** [comment]
This issue was moved to SkygearIO/guides#2
