### ISSUE TITLE
[Design Update] Pin the side menu on large screen

### ISSUE THREAD

**Issue by ben181231** [SkygearIO/skygear-doc#494]
The responsiveness will be:

1. Large screen / Smaller screen - Pin on the left and scroll separately.
2. Mobile - Become hamburger menu

Design: [desktop](https://github.com/SkygearIO/skygear-doc/files/802765/SkygearDoc.Guides.Design.-20170223.-wcm.pdf) and  [mobile](https://github.com/SkygearIO/skygear-doc/files/796141/SkygearDoc.Guides.Design.Mobile.-20170223.pdf)

**Comment by ben181231** [comment]
This task is split from #462.

**Comment by chpapa** [comment]
Now if I scroll down the side menu to bottom, and click a guide (let's say "Error Handling" under Cloud Functions"), the new page will load, the the side menu jump to the bottom.

This behaviour is annoying. Can we make the side menu stay where it is when page switch? Or if it is too difficult, maybe we can jump the side menu to the line of the current guide at least...

**Comment by chpapa** [comment]
@ben181231 @rickmak Actually I have added comments above and moved the issue back to WIP. Please only consider this issue fix after the above have been addressed.

**Comment by ben181231** [comment]
The updates needed:

- Make the platform icons smaller. 
- Make the platform icons sticky. 
- Do not re-render the menu when change page. 

@chpapa Am I correct ?

**Comment by chpapa** [comment]
Yap
