### ISSUE TITLE
[Design Update] Add document ToC

### ISSUE THREAD

**Issue by ben181231** [SkygearIO/skygear-doc#496]
The responsiveness will be:
1. Large screen - Pin on the right of the document and not scroll with the document.
2. Smaller screen / Mobile screen - Move to the top of the document.

For the ToC generation, may use [this plugin](https://www.npmjs.com/package/markdown-it-table-of-contents)

Design: [desktop](https://github.com/SkygearIO/skygear-doc/files/802765/SkygearDoc.Guides.Design.-20170223.-wcm.pdf) and  [mobile](https://github.com/SkygearIO/skygear-doc/files/796141/SkygearDoc.Guides.Design.Mobile.-20170223.pdf)

**Comment by ben181231** [comment]
This task is split from #462.

**Comment by chpapa** [comment]
Now if I clicked a section in TOC, the section name will be highlighted in blue. But if I scroll the main content to another part, the highlight won't change.

Is it possible to make the highlight change with the main content?

If it is really impossible or very difficult, let's see if we can not highlight to make it feel better?

**Comment by chpapa** [comment]
@ben181231 @rickmak Actually I have added comments above and moved the issue back to WIP. Please only consider this issue fix after the above have been addressed.

**Comment by ben181231** [comment]
@chpapa Okay. I am going to remove the highlight first.

**Comment by chpapa** [comment]
@ben181231 please let us look at it when you do that quick fix (and open another issue for that?) to see if it actually works as a quick fix.
