### ISSUE TITLE
Do not include guides as a submodule of this repo

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-doc#530]

**Comment by rickmak** [comment]
Do you mean to publish this repo as display package on npm. The release should be managed at guide repo branch or tag. It will make the content control the delivery, not style/display control the delivery. Which makes more sense to me.

**Comment by cheungpat** [comment]
Not decided how yet, the easy way out is to add this repo as a submodule of `guides`, so that we don’t need to publish this repo as an npm package.

Agree on this, this is also my intention:

> It will make the content control the delivery, not style/display control the delivery. Which makes more sense to me.

**Comment by chpapa** [comment]
Actually have this repo publish as a package to compile guides repo into HTML could be a good idea, so developers / content can preview what their wrote easier (now a lot of time I think people don't really preview it before they commit)

I have seen a few open sources project have publish a nom package with command line to turn a folder of docs into a folder of HTML, not sure if that is what @rickmak meant as _display package_

**Comment by cheungpat** [comment]
the issue as captioned has since been fixed
