### ISSUE TITLE
Improve doc organization

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/skygear-doc#550]
### py-skygear
- Update `scripts/before-deploy.sh` not to remove python doc at https://docs.skygear.io/py/reference/master/
- Update api-reference page to include py-skygear doc

### chat js sdk
- Update chat JS SDK to separate client and cloud api like js core sdk
- Update api-reference page to have chat cloud function js api reference which link to chat JS SDK like core

**Comment by howawong** [comment]
chat-SDK-JS latest doc issue should be fixed by now as I just updated the latest tag.
Please take a look at
https://docs.skygear.io/js/chat/reference/latest/class/lib/cloud.js~SkygearChatCloudContainer.html
