### ISSUE TITLE
Submenu don't work with link

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-doc#59]
Currently:

- The submenu only work with `#anchor`. If the content of the submenu is linked to a full link. The active state will be wrong.

Expect:

- Both menu and submenu can be a point to anchor or full url. Both should just work fine with the display state.

**Comment by david90** [comment]
For now I will continue to restructure the pages into a single page with #anchor first.

**Comment by david90** [comment]
Fixed
