### ISSUE TITLE
Add "Coming Soon" placeholder text for pages "Not Found" to avoid readers feeling confused

### ISSUE THREAD

**Issue by joyzoursky** [SkygearIO/skygear-doc#77]
Suggested copywriting for not-existing pages:

### Coming Soon
Thanks for using Skygear. Please check back later for new updates.

**Comment by royuen** [comment]
- [ ] iOS Records
- [ ] JS Queries
- [ ] JS Pubsub
- [ ] JS Access control
- [ ] JS React JS integration
- [ ] Plugins

**Comment by joyzoursky** [comment]
Found that these two pages are still showing Not Found.
- [ ] https://docs.skygear.io/contributing
- [ ] https://docs.skygear.io/faq

**Comment by joyzoursky** [comment]
Tutorial is also Not Found.
https://docs.skygear.io/tutorial

**Comment by royuen** [comment]
- Guide => Quick Start
- Tutorial => Sample project => Quip to list of example projects
- API reference => generate and host it if we can compile, otherwise delete it first
- Inner page coming soon => Put it in content rather than a new page

**Comment by chpapa** [comment]
Closing #311 #310 #307 #306 since I suppose we will remove Skygear Server API reference page, CLI API reference page, Javascript API reference page, and replace Tutorial page button after this issue is completed.

**Comment by royuen** [comment]
- [ ] Remaining cloud code first 3 pages
