### ISSUE TITLE
include link to skygear server setup on SDKs getting started

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-doc#79]
To hint the reader that they need to install the server before working with the SDK, e.g. setting up API key

**Comment by chpapa** [comment]
For simplicity, I think it is better if we use managed hosting for getting started, instead of teach new comers to set up everything locally.

**Comment by bensonby** [comment]
This section should be put in the server guide. It is not necessary to have a link in "getting started" because we assume the user will use the managed hosting
