### ISSUE TITLE
Missing menu on small screen

### ISSUE THREAD

**Issue by ben181231** [SkygearIO/skygear-doc#84]
- [x] Sticky Header
- [x] Hamburger Menu

**Comment by rickmak** [comment]
I think it is serious. It worse than no responsive.

**Comment by TakLee96** [comment]
I also notice this issue when I try to look at the doc page on my phone.

**Comment by rickmak** [comment]
The menu scroll to position is not correctly calculate after adding the top menu.

![img_9291](https://cloud.githubusercontent.com/assets/62677/16906101/f4136b10-4ce3-11e6-8db7-34532cba1eba.jpg)
