### ISSUE TITLE
Support Swift/Obj-C code tab switching

### ISSUE THREAD

**Issue by david90** [SkygearIO/skygear-doc#87]
on iOS docs

**Comment by bensonby** [comment]
to study how this can be done with `marked` and currect doc site architecture

**Comment by david90** [comment]
Discussed with @ben181231 that we can use custom <div>s to mark down in the document.

ref: https://daringfireball.net/projects/markdown/syntax#html

**Comment by ben181231** [comment]
So to make the multilingual code block in markdown, it would be like:

```
<div class="multilingual-code-block">
    ```swift
        // Swift Code
    ```

    ```Obj-C
        // Objective C Code
    ```
</div>
```

@david90 @bensonby, right?

**Comment by bensonby** [comment]
Added through 362edfc.

It will combine any two consecutive language blocks of different languages as a code switcher
